version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file nexus_finalcf.yml --s3-bucket cicdinput --output-template-file nexusSamTemplate.yml
#
artifacts:
      type: zip
      files:
      - nexus_finalcf.yml
      - nexusSamTemplate.yml
secondary-artifacts:
    artifact2:
      type: zip
      files:
        - nexus_finalcf.yml
        - nexusSamTemplate.yml
      name: artifact2
      base-directory: $CODEBUILD_SRC_DIR_artifact2