version: 0.2
phases:
  install:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket cicdinput --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml