version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file nexus_finalcf.yml --s3-bucket cicdinput --output-template-file nexusSamTemplate.yml
#      - cd $CODEBUILD_SRC_DIR
#      - touch file1
#      - cd $CODEBUILD_SRC_DIR_artifact2
#      - touch file2

#working code
artifacts:
      type: zip
      files:
      - nexus_finalcf.yml
      - nexusSamTemplate.yml
secondary-artifacts:
    artifact21:
      type: zip
      files:
        - file2
      name: artifact2
      base-directory: $CODEBUILD_SRC_DIR_artifact2