version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file nexus_cf2.yml --s3-bucket cicdinput --output-template-file nexusSamTemplate.yml
artifacts:
  type: zip
  files:
    - nexus_cf2.yml
    - nexusSamTemplate.yml