version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file nexus_finalcf.yml --s3-bucket cicdinput --output-template-file nexusSamTemplate.yml
#
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR_nexusbuild
      type: zip
      files:
      - nexus_finalcf.yml
      - nexusSamTemplate.yml
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_nexusbuild
      type: zip
      files:
        - nexus_finalcf.yml
        - nexusSamTemplate.yml