version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file nexus_finalcf.yml --s3-bucket cicdinput --output-template-file nexusSamTemplate.yml
#working
artifacts:
      type: zip
      files:
      - nexus_finalcf.yml
      - nexusSamTemplate.yml
secondary-artifacts:
    artifact21:
      type: zip
      files:
        - nexus_finalcf.yml
        - nexusSamTemplate.yml
      name: artifact-$(date +%Y-%m-%d)
      base-directory: $CODEBUILD_SRC_DIR_artifact-$(date +%Y-%m-%d)